[package]
name = "Ashfall"
description = "A camping, survival and needs mod for Morrowind."
homepage = "https://www.nexusmods.com/morrowind/mods/49057"
repository = "https://github.com/jhaakma/ashfall"
authors = [ "Merlord",]
version = "3.10.1"

[dependencies]
assets = [ "Ashfall.esp", "Icons/ashfall", "Meshes/ashfall", "MWSE/mods/mer/ashfall", "Sound/ashfall", "Textures/Ashfall",]

[dependencies.mwse]
buildnumber = 3066

[dependencies.mge-xe]
version = ">=0.15.0"

[tools.mwse]
lua-mod = "mer.ashfall"

[dependencies.mods."Skills Module"]
mwse-module = "OtherSkills"
url = "https://www.nexusmods.com/morrowind/mods/46034?tab=files"

[dependencies.mods."The Crafting Framework"]
mwse-module = "CraftingFramework"
version = "^1.7.4"
url = "https://www.nexusmods.com/morrowind/mods/51009?tab=files"
