name: Package Ashfall
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 50

      - name: Build Project
        uses: edgarrc/action-7z@v1
        with:
          args: 7z a Ashfall.7z "Data Files"
   
      - name: Create Release
        uses: notlmn/release-with-changelog@v2
        with:
          header: '### Changelog'
          include-hash: true
          include-range: true
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload to Github
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: Ashfall.7z
